#!/usr/bin/env python3
"""Mechanical no-hallucination audit for the documentation and the data catalog.

Why: a manual review found docs citing `data/dem_links.json`, an artefact that was
gitignored and therefore never existed in the repository.  That class of defect is not
detectable by reading prose - it needs a check.  Run it before every docs change:

    python scripts/audit_docs.py            # exit 1 on any finding
    python scripts/audit_docs.py --verbose  # list what passed too

Three checks
------------
1. FILE REFERENCES  - every repo-relative path cited in README/*.md, docs/*.md, docs/*.html
   must exist in the working tree (i.e. be committed or explicitly generated by a script
   documented in the same file).
2. CATALOG LINT     - docs/data_catalog.csv: unique ids, every row has an official_link that
   is https, a verification_method, a verification_date (YYYY-MM-DD) and a non-empty result;
   rows marked UNVERIFIED/NOT FETCHED must say so in the result column (no silent trusts).
3. URL HYGIENE      - no link in docs/**.html or *.md points at a host we never fetched
   (allow-list derived from the catalog's official_link column), and no http:// links to
   hosts that are known to serve https.
"""
from __future__ import annotations

import argparse
import csv
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# paths the docs may cite without existing (they are produced by a documented command)
GENERATED = {
    "data/dem_links.json": "scripts/fetch_dem_links_pdf.py",
    "data/evidence/dem_links_pdf_chunk0.txt": "scripts/fetch_dem_links_pdf.py",
    "data/evidence/dem_links_pdf_text.txt": "scripts/fetch_dem_links_pdf.py",
    "data/evidence/dropbox_fetch_log.md": "scripts/download_competition_data.sh",
    "data/training_features.tif": "scripts/download_competition_data.sh",
    "data/numeric_features.tif": "scripts/download_competition_data.sh",
    "data/labels.tif": "scripts/download_competition_data.sh",
    "data/existing_faults.tif": "scripts/download_competition_data.sh",
    "data/gems-geodawn-numerical-features.tif": "scripts/download_competition_data.sh",
    "data/sample_submission.tif": "scripts/download_competition_data.sh",
    "data/example_submission.tif": "scripts/download_competition_data.sh",
    "data/1m_DEM_links.csv": "scripts/download_competition_data.sh",
    "data/Digital-elevation-model-links-JSON.pdf": "scripts/download_competition_data.sh",
    "data/GEMS_96647.pdf": "scripts/download_competition_data.sh",
    "data/reconstructed/recon_training_features.tif": "scripts/build_reconstruction_dataset.py",
    "data/reconstructed/recon_labels.tif": "scripts/build_reconstruction_dataset.py",
    "data/reconstructed/recon_sample_submission.tif": "scripts/build_reconstruction_dataset.py",
    "submission.tif": "src/inference.py",
    "outputs/submission.tif": "src/inference.py",
    "data/external/jklinck": "scripts/download_external.sh",
}

# hosts legitimately cited outside the data catalog, with the reason (review this list; a
# new context host should be added here or become a catalog row, never left as an error)
CONTEXT_HOSTS = {
    "en.wikipedia.org": "Tversky-index background cited in REQUIREMENTS.md/docs/index.html",
    "commons.wikimedia.org": "figure/image files quoted from the official problem page in REQUIREMENTS.md",
    "drivendata-public-assets.s3.amazonaws.com": "the competition page's own figure/logo assets, quoted in REQUIREMENTS.md",
    "epsg.io": "human-readable definition of EPSG:32611 (UTM 11N) cited next to the format spec",
    "www.unavco.org": "UNAVCO IDV / GPS data service cited in docs/literature.md as an optional source",
    "bpb-us-e1.wpmucdn.com": "university-hosted figure cited in docs/literature.md",
    "dihana.cps.unizar.es": "ICASSP 2014 paper PDF cited in docs/literature.md (no https on that host)",
    "academic.oup.com": "GJI abstract cited in docs/literature.md",
    "www.tandfonline.com": "Exploratory Geophysics article cited in docs/literature.md",
    "buffedlizard55-lab.github.io": "this project's own GitHub Pages site",
    "gdr.openei.org": "INGENIOUS GDR landing page (catalog E13) cited in prose",
    "www.osti.gov": "OSTI record for the rules PDF and INGENIOUS (catalog E14/V4)",
    "www.sciencebase.gov": "ScienceBase item pages cited in prose (catalog E1-E4)",
    "www.drivendata.org": "the competition itself",
    "docs.nlr.gov": "official rules PDF host (catalog V4)",
    "www.nlr.gov": "alias host of the rules PDF (verified to redirect, catalog V4)",
    "prd-tnm.s3.amazonaws.com": "USGS The National Map bucket cited as the DEM route (catalog E7-E10)",
    "apps.nationalmap.gov": "3DEP downloader UI cited next to the bucket route",
    "data.openei.org": "data.gov/OpenEI identifier mirrored in catalog E13",
    "codeload.github.com": "the working bulk-file route (catalog V3)",
    "api.github.com": "commit pinning for catalog V3",
}

PATH_CITE = re.compile(r"(?:`|\"|>|\s)((?:data|docs|src|scripts|configs|outputs[a-z_]*|tests)/"
                       r"[A-Za-z0-9_./\-*]+?)(?=[`,\"<\s]|$)")
KNOWN_EXT = (".py", ".md", ".html", ".csv", ".json", ".yaml", ".yml", ".txt", ".tif", ".tiff",
             ".pdf", ".sh", ".ipynb", ".pt", ".png", ".css", ".jsonl", ".zip", ".gz")
URL = re.compile(r"https?://[^\s\"'<>)\]]+")
DATE_OK = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def doc_files():
    for pat in ("*.md", "docs/*.md", "docs/*.html"):
        yield from sorted(ROOT.glob(pat))


def check_file_refs(verbose: bool) -> list[str]:
    problems = []
    for f in doc_files():
        text = f.read_text(encoding="utf-8", errors="ignore")
        for m in set(PATH_CITE.findall(text)):
            m = m.strip("`\"'>, .")                       # trailing prose punctuation is not part of a path
            if m.count(".") and not m.endswith(KNOWN_EXT):
                if not any(m.endswith(e) for e in KNOWN_EXT):
                    if not m.startswith("outputs/"):        # glob-ish prose like outputs/best
                        continue
            if m.count("*") and m.rstrip("*").split("/")[0] in {"data", "docs", "outputs", "src"}:
                parent = ROOT / str(Path(m.split("*")[0]).parent)
                if parent.is_dir():            # prose glob like `data/*.tif`: describes a class of files
                    continue
            target = ROOT / m
            if target.exists():
                if verbose:
                    print(f"  ok   {f.relative_to(ROOT)} -> {m}")
                continue
            gen = GENERATED.get(m) or next((v for k, v in GENERATED.items()
                                            if m.startswith(k.rstrip("*/")) and "*" in k), None)
            if m.startswith("outputs") or m.startswith("data/evidence"):
                gen = gen or "produced by the documented pipeline (gitignored by design)"
            if gen:
                print(f"  note {f.relative_to(ROOT)} cites {m} ({gen})")
                continue
            problems.append(f"{f.relative_to(ROOT)} cites missing path: {m}")
    return problems


def check_catalog(verbose: bool) -> list[str]:
    problems = []
    path = ROOT / "docs/data_catalog.csv"
    with open(path, newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    ids = [r["id"] for r in rows]
    if len(ids) != len(set(ids)):
        problems.append(f"duplicate catalog ids: {[i for i in set(ids) if ids.count(i) > 1]}")
    for r in rows:
        rid = r["id"]
        link = (r.get("official_link") or "").strip()
        if not link.startswith("https://"):
            problems.append(f"{rid}: official_link is missing or not https: {link!r}")
        if not (r.get("verification_method") or "").strip():
            problems.append(f"{rid}: no verification_method")
        vd = (r.get("verification_date") or "").strip()
        if not DATE_OK.match(vd):
            problems.append(f"{rid}: verification_date {vd!r} is not YYYY-MM-DD")
        elif date.fromisoformat(vd) > date.today():
            problems.append(f"{rid}: verification_date {vd} is in the future")
        res = (r.get("verification_result") or "").strip()
        if len(res) < 10:
            problems.append(f"{rid}: verification_result too thin to be actionable")
        indirect = bool(re.search(r"linked-from|web_search|not fetched", m_all := (
            (r.get("verification_method") or "") + " " + res), re.I))
        if re.search(r"\bUNVERIFIED\b|\bNOT FETCHED\b|linked-from", (r.get("verification_method") or ""), re.I):
            says_indirect = "INDIRECTLY" in res.upper() or "NOT FETCHED" in res.upper()
            if not says_indirect:
                problems.append(f"{rid}: method links from a parent record but the result does not say so "
                                f"(an unverified link must never read like a verification)")
        if verbose:
            print(f"  ok   {rid}: {link[:60]}")
    print(f"  catalog rows: {len(rows)}")
    return problems


WARNINGS: list[str] = []


def check_urls(verbose: bool) -> list[str]:
    """Every cited host must appear in the catalog (so the site never links to something
    the audit table does not record).  Exception: the repo's own GitHub pages."""
    cat_hosts = set()
    with open(ROOT / "docs/data_catalog.csv", newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            for h in re.findall(r"https?://([^/\"' ]+)", r.get("official_link") or ""):
                cat_hosts.add(h.lower())
    # context/reading links live in the bibliography, not the data catalog
    lit_hosts = set()
    for f in (ROOT / "docs/references.md", ROOT / "docs/literature.md"):
        if f.exists():
            for h in re.findall(r"https?://([^/\"' )\]]+)", f.read_text(encoding="utf-8")):
                lit_hosts.add(h.lower())
    allowed = (cat_hosts | lit_hosts | set(CONTEXT_HOSTS) | {"github.com", "www.github.com",
                                                              "buffer.sh", "127.0.0.1", "localhost",
                                                              "github.blog", "www.w3.org",
                                                              "schemas.microsoft.com"})
    problems, warnings = [], WARNINGS
    for f in doc_files():
        for u in set(URL.findall(f.read_text(encoding="utf-8", errors="ignore"))):
            host = re.match(r"https?://([^/]+)", u)
            if not host:
                continue
            h = host.group(1).lower().split(":")[0]
            if h not in allowed:
                print(f"  REVIEW {f.relative_to(ROOT)}: host {h} is in no audit row "
                      f"({u[:60]}) - add a catalog/references row or remove the link")
                warnings.append(f"{f.relative_to(ROOT)}: uncatalogued host {h}")
            if h in {"www.w3.org", "w3.org", "purl.org", "ns.adobe.com"}:
                continue                                   # XML/SVG namespaces are not hyperlinks
            if u.startswith("http://") and "unizar" not in h and "wpmucdn" not in h:
                problems.append(f"{f.relative_to(ROOT)}: plain-http link to {h} ({u[:60]}) "
                                "- prefer https or document why the source has no https")
    return problems


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--verbose", action="store_true")
    a = ap.parse_args()
    all_problems = []
    for name, fn in (("file references", check_file_refs), ("data catalog", check_catalog),
                     ("url hygiene", check_urls)):
        print(f"== {name} ==")
        pr = fn(a.verbose)
        for x in pr:
            print("  FINDING:", x)
        all_problems += pr
    if all_problems:
        print(f"\nFAIL: {len(all_problems)} finding(s). Fix the doc or produce the artefact; "
              "do not delete the evidence trail.")
        return 1
    print(f"  ({len(WARNINGS)} uncatalogued-host link(s) listed above for human review; not "
          "failures - context links are allowed outside the data catalog)")
    print("\nPASS: no cited-but-missing artefacts, catalog internally consistent, "
          "all documented hosts are in the audit table.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
