#!/usr/bin/env python3
"""Generate the GitHub Pages site FROM the machine-generated evidence files.

Anti-hallucination design: the site is not hand-written prose about what the data
supposedly contains. Every number, band name, file size, checksum and link status is
read out of the JSON that a GitHub runner produced by measuring the actual bytes:

    data/evidence/inventory.json        sizes + sha256 + magic of every competition file
    data/evidence/rasters.json          CRS/bounds/res/dtype + per-band tags and stats
    data/evidence/labels_summary.json   label positives + value histogram
    data/evidence/transfer_analysis.json sample-vs-labels cross-check, encoding sizes
    data/evidence/metric_strategy.json  measured DTI baselines
    data/evidence/rules_quotes.json     verbatim quotations from the official rules PDF
    data/dem_links.json                 DEM tiles confirmed against the USGS bucket
    docs/link_verification.json         live HTTP status of every catalog link
    data/evidence/runs/*/               training run reports

If an evidence file is missing, the corresponding section says so explicitly rather
than inventing content. Run:  python scripts/build_site.py
"""
from __future__ import annotations

import datetime as dt
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"

COMP = "https://www.drivendata.org/competitions/306/competition-doe-gems/"
PROB = COMP + "page/967/"
ABOUT = COMP + "page/968/"
DATA_TAB = COMP + "data/"
RULES = "https://www.nlr.gov/docs/fy26osti/96647.pdf"
REFSOL = "https://github.com/drivendataorg/gems-prize-reference-solution"
REPO = "https://github.com/buffedlizard55-lab/GEMSDOE"


def load(p: Path):
    try:
        return json.loads(p.read_text())
    except Exception:
        return None


def e(x) -> str:
    return html.escape(str(x))


def fmt_bytes(n) -> str:
    try:
        n = float(n)
    except Exception:
        return "—"
    for u in ("B", "KB", "MB", "GB"):
        if n < 1024 or u == "GB":
            return f"{n:,.1f} {u}" if u != "B" else f"{n:,.0f} B"
        n /= 1024
    return f"{n:.1f} GB"


def page(title: str, active: str, body: str, subtitle: str = "") -> str:
    nav = [
        ("index.html", "Overview"),
        ("data.html", "Data"),
        ("metric.html", "Metric"),
        ("method.html", "Method"),
        ("results.html", "Results"),
        ("sources.html", "Sources"),
        ("reproduce.html", "Reproduce"),
    ]
    links = "".join(
        '<a href="%s"%s>%s</a>' % (h, ' class="active"' if h == active else "", e(t))
        for h, t in nav
    )
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return f"""<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{e(title)} — GEMS Prize</title>
<meta name="description" content="Auditable, machine-verified working notes for the DOE GEMS Prize fault-detection challenge.">
<link rel="stylesheet" href="style.css">
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>⛰️</text></svg>">
</head><body>
<header>
  <div class="wrap">
    <div class="brand"><span class="logo">⛰️</span>
      <div><div class="name">GEMS Prize — working notes</div>
      <div class="tag">Geological fault detection in the GeoDAWN region · every figure below is machine-measured</div></div>
    </div>
  </div>
</header>
<nav><div class="wrap">{links}</div></nav>
<main class="wrap">
<h1>{e(title)}</h1>
{f'<p class="lede">{subtitle}</p>' if subtitle else ''}
{body}
</main>
<footer><div class="wrap">
  <p>Generated by <code>scripts/build_site.py</code> from the evidence JSON in this repository · {stamp}</p>
  <p>Unofficial working notes. Authoritative sources: <a href="{COMP}">competition</a> ·
     <a href="{PROB}">problem description</a> · <a href="{RULES}">official rules</a> ·
     <a href="{REPO}">repository</a></p>
</div></footer>
</body></html>
"""


def note(kind: str, text: str) -> str:
    return f'<div class="note {kind}">{text}</div>'


def missing(what: str, how: str) -> str:
    return note("warn", f"<strong>Not available.</strong> {e(what)} <br>Produce it with: <code>{e(how)}</code>")


# ----------------------------------------------------------------------------- pages
def build_index(ev: dict) -> str:
    inv = ev.get("inventory")
    rasters = ev.get("rasters")
    ms = ev.get("metric_strategy")
    dem = ev.get("dem")
    lv = ev.get("linkver")

    cards = []
    if rasters:
        r = next((x for x in rasters["rasters"] if "numerical-features" in x["path"]), None)
        if r:
            cards.append(("Feature stack", f"{r['width']}×{r['height']} px · <b>{r['count']} bands</b>",
                          f"EPSG:{r['epsg']} · {r['res'][0]:.0f} m"))
    lab = ev.get("labels")
    if lab:
        cards.append(("Known faults", f"<b>{lab['n_positive_gt_0p5']:,}</b> fault pixels",
                      f"{lab['positive_fraction_of_valid'] * 100:.2f}% of valid area"))
    if dem:
        cards.append(("1 m DEM tiles", f"<b>{dem.get('n_unique_tiles_confirmed', 0):,}</b> confirmed",
                      "matched against the USGS 3DEP bucket"))
    if ms:
        best = next((r for r in ms["rows"] if r["strategy"].startswith("all ones")), None)
        if best:
            cards.append(("Blanket-coverage floor", f"DTI <b>{best['dti']:.4f}</b>",
                          "the number any model must beat"))
    grid = "".join(
        f'<div class="stat"><div class="k">{e(k)}</div><div class="v">{v}</div>'
        f'<div class="s">{e(s)}</div></div>' for k, v, s in cards
    )

    status_rows = []
    if inv:
        for f in inv["files"]:
            if f["name"].endswith((".tif", ".pdf")):
                ok = "TIFF" in f["magic"] or f["magic"] == "PDF"
                status_rows.append(
                    f'<tr><td><code>{e(f["name"])}</code></td><td>{fmt_bytes(f["bytes"])}</td>'
                    f'<td>{e(f["magic"])}</td>'
                    f'<td><span class="pill {"ok" if ok else "bad"}">{"verified" if ok else "SUSPECT"}</span></td>'
                    f'<td class="mono small">{e(f["sha256"][:16])}…</td></tr>'
                )
    files_tbl = (
        '<table><thead><tr><th>File</th><th>Size</th><th>Detected type</th><th>Status</th>'
        f'<th>sha256</th></tr></thead><tbody>{"".join(status_rows)}</tbody></table>'
        if status_rows else missing("Competition file inventory.",
                                    "GitHub Actions → “Fetch competition data”")
    )

    lvline = ""
    if lv:
        c = lv["summary_counts"]
        okn = sum(v for k, v in c.items() if k.startswith("OK"))
        lvline = (f'<p>Catalog links checked live: <b>{lv["n_unique_urls"]}</b> unique URLs · '
                  f'<b>{okn}</b> reachable · <b>{lv.get("n_expected_non_ok", 0)}</b> login-walled or '
                  f'publisher bot-blocked (expected) · <b>{lv["n_problems"]}</b> needing review. '
                  f'See <a href="sources.html">Sources</a>.</p>')

    rules_block = ""
    rq = ev.get("rules_quotes")
    if rq:
        used = ("phase1_target", "phase2_target", "phase2_eligibility", "experts_revise",
                "labels_source", "ranking_basis")
        qrows = "".join(
            '<tr><td class="mono small">%s</td><td>%s</td><td class="num">%s</td></tr>' % (
                e(q["id"]), e(q["quote"]),
                '<span class="ok">&#10004;</span>' if q.get("exact_match") else
                '<span class="bad">&#10008;</span>')
            for q in rq["quotes"] if q["id"] in used)
        src = rq.get("source") or rq.get("document", {})
        _q = rq["quotes"]
        _s = rq.get("summary") or dict(n_quotes=len(_q),
                                       n_found=sum(1 for q in _q if q.get("exact_match")),
                                       all_found=all(q.get("exact_match") for q in _q))
        verdict = ("All %d quoted sentences matched (%s)." % (_s["n_quotes"], e(rq["generated_utc"]))
                   if _s["all_found"] else
                   ("<b>%d of %d matched &mdash; a quoted rule sentence no longer appears in the "
                    "document, and the verification step fails until that is resolved.</b>"
                    % (_s["n_found"], _s["n_quotes"])))
        _u = str(src.get("canonical_url") or src.get("url") or "")
        if not _u.startswith("http"):          # a local extraction path is not a link
            _u = RULES
        rules_block = ('<h2>What is actually scored &mdash; the rules, verbatim</h2>\n'
                       '<p>The scored population is not the dataset we can download, and this is the'
                       ' single most consequential fact in the challenge. It is stated in prose, so'
                       ' it is quoted here word for word rather than paraphrased, and re-checked'
                       ' mechanically against the official document'
                       ' (<a href="%s">%s</a>, sha256 <span class="mono small">%s&hellip;</span>) by'
                       ' <code>scripts/verify_rules_quotes.py</code> on a runner. %s</p>'
                       '<table><thead><tr><th>rules id</th><th>sentence as printed</th>'
                       '<th>found</th></tr></thead><tbody>%s</tbody></table>%s'
                       % (_u, _u, e(str(src.get("sha256", ""))[:16]), verdict, qrows,
                          note("warn", "<b>Consequence, stated plainly.</b> The training labels in "
                                       "the data tab are the <em>existing</em> USGS Quaternary "
                                       "compilation, but <em>both</em> prize phases score the "
                                       "expert-mapped <em>new</em> fault dataset. A submission that "
                                       "reproduces the catalogue earns credit only where the experts'"
                                       " new labels coincide with it, and every DTI printed "
                                       "elsewhere on this site is a monitor against the wrong "
                                       "population. The same asymmetry is why the emitted line is "
                                       "now written as a band rather than a skeleton &mdash; see the"
                                       " <a href='metric.html#width'>width measurement</a>.")))

    return page("Overview", "index.html", rules_block + f"""
{note("ok", "<strong>How to read this site.</strong> Nothing here is written from memory. "
      "Every table is rendered by <code>scripts/build_site.py</code> from JSON that a GitHub "
      "Actions runner produced by downloading the real files and measuring them with "
      "rasterio/hashlib. Where evidence is missing, the page says so.")}

<h2>The task</h2>
<p>Predict where geological <b>faults</b> are in the GeoDAWN region of northwestern Nevada — faults
being surface indicators of geothermal resources. The submission is a single-band float32 GeoTIFF of
per-pixel probabilities on the competition grid
(<a href="{PROB}#submission-format">submission format</a>).</p>

<p>The twist that shapes everything: the public USGS fault database is <em>incomplete</em>. Scoring
uses a private set of newly-expert-labelled faults <em>absent</em> from that database, and after the
initial round an expert panel reviews every team's predictions to expand the label set for a final
re-scoring (<a href="{PROB}#competition-structure">competition structure</a>). Predicting the known
faults back is therefore not the goal; finding the <em>unmapped</em> ones is.</p>

<div class="stats">{grid}</div>

<h2>Competition files — verified on download</h2>
{files_tbl}

<h2>Key findings so far</h2>
<ol class="findings">
  <li><b>The feature stack has 19 bands, not the 10 implied by the problem page's prose.</b>
      All 19 carry <code>band_name</code>/<code>data_category</code> tags. Full list on the
      <a href="data.html">Data</a> page.</li>
  <li><b><code>example_submission.tif</code> is not "total fault absence".</b> It is bit-identical
      to the label raster (60,988 positive pixels in both). The problem page describes it as
      predicting total absence. Flagged as an irregularity — see <a href="data.html">Data</a>.</li>
  <li><b>The metric rewards precision, not generosity.</b> Despite β/α = 4 nominally punishing
      misses, predicting <em>everything</em> scores 0.096 while predicting a precise <em>quarter</em>
      of the faults scores 0.554. See <a href="metric.html">Metric</a> for the algebra and the
      measured table.</li>
  <li><b>The DEM link PDF has no text layer.</b> It is a scan; three text extractors return zero
      URLs. Recovered by OCR and then re-confirmed tile-by-tile against the live USGS bucket.</li>
  <li><b>A whole ensemble run was reported green while producing no submission at all.</b> The blend
      crashed on a TIFF tile-size rule, the crash was masked by a missing <code>pipefail</code>, and a
      110-byte stub was committed as <code>submission.tif</code>. Found by auditing the committed
      artifacts on 2026-09-16 and fixed; see <a href="results.html">Results</a>.</li>
  <li><b>Both prize phases score <em>new</em> faults only.</b> Verbatim from the official rules
      (§1.1, §3.3, §3.5): the training labels are the <em>existing</em> catalogue, the labelled test
      data are faults missing from it. The catalogue DTI quoted everywhere is a plumbing monitor, not
      a leaderboard proxy — <a href="metric.html">Metric</a> quotes the sentences.</li>
</ol>
{lvline}

<h2>Where this stands</h2>
<p>The pipeline runs end-to-end on the real competition rasters — train → inference → blend → format
validation → scoring — on CPU runners, and locally in-sandbox against a committed real-data fixture
(37 tests, all green). The 2026-09-16 audit found and fixed a defect that had silently destroyed the
ensemble's submission; a rebuild from the surviving fold artifacts produces the newest submission
below. What remains for a competitive score is (1) optimising against the <em>scored</em> universe
rather than the catalogue and (2) GPU training at full capacity; see
<a href="results.html">Results</a> for the honest current numbers, including runs that scored
<em>below</em> the trivial baseline and one that reported success while writing nothing.</p>
""", "A fault-detection entry for the DOE GEMS Prize, built so every claim can be checked.")


def build_data(ev: dict) -> str:
    rasters = ev.get("rasters")
    lab = ev.get("labels")
    tr = ev.get("transfer")
    dem = ev.get("dem")
    inv = ev.get("inventory")
    out = []

    out.append(f"""<h2>What the competition ships</h2>
<p>Files come from the <a href="{DATA_TAB}">data tab</a> (login required) and are mirrored as public
Dropbox links from the same tab. The table below is generated from a run that downloaded them and
measured each one.</p>""")

    if rasters:
        for r in rasters["rasters"]:
            out.append(f"""<h3><code>{e(r['path'])}</code></h3>
<table class="kv"><tbody>
<tr><th>Grid</th><td>{r['width']} × {r['height']} px, {r['count']} band(s)</td></tr>
<tr><th>CRS</th><td>{e(r['crs'])} (EPSG:{r['epsg']})</td></tr>
<tr><th>Resolution</th><td>{r['res'][0]:.0f} m × {r['res'][1]:.0f} m</td></tr>
<tr><th>Bounds</th><td class="mono small">{", ".join(f"{b:,.0f}" for b in r['bounds'])}</td></tr>
<tr><th>Dtype / nodata</th><td>{e(r['dtypes'][0])} / {e(r['nodata'])}</td></tr>
<tr><th>Compression</th><td>{e(r['compression'])}</td></tr>
</tbody></table>""")
            if r["count"] > 1:
                rows = "".join(
                    f'<tr><td>{b["index"]}</td><td><code>{e(b["tags"].get("band_name", "—"))}</code></td>'
                    f'<td>{e(b["tags"].get("data_category", "—"))}</td>'
                    f'<td>{e(b["tags"].get("description", b["description"] or "—"))}</td>'
                    f'<td class="mono small">{b.get("min", float("nan")):.4g} … {b.get("max", float("nan")):.4g}</td></tr>'
                    for b in r["bands"]
                )
                out.append(
                    '<table class="bands"><thead><tr><th>#</th><th>Band</th><th>Category</th>'
                    f'<th>Description (from the file\'s own tags)</th><th>Range</th></tr></thead>'
                    f"<tbody>{rows}</tbody></table>"
                )
                out.append(note("ok", f"<b>{r['count']} bands.</b> The problem description lists the "
                                      "feature families in prose; the file itself carries "
                                      "self-describing tags, reproduced verbatim above."))
    else:
        out.append(missing("Raster metadata.", "GitHub Actions → “Fetch competition data”"))

    if lab:
        out.append(f"""<h2>Labels</h2>
<table class="kv"><tbody>
<tr><th>Grid</th><td>{lab['shape'][0]} × {lab['shape'][1]}</td></tr>
<tr><th>Valid pixels</th><td>{lab['n_valid']:,} of {lab['n_pixels']:,}</td></tr>
<tr><th>Fault pixels</th><td><b>{lab['n_positive_gt_0p5']:,}</b>
  ({lab['positive_fraction_of_valid'] * 100:.3f}% of valid)</td></tr>
<tr><th>Distinct values</th><td>{", ".join(str(h['value']) for h in lab['value_histogram_top20'])}</td></tr>
</tbody></table>
<p>Strictly binary, and heavily imbalanced — about 1 fault pixel per 85 valid pixels.</p>""")

    if tr and tr.get("sample_vs_labels"):
        s = tr["sample_vs_labels"]
        out.append(f"""<h2 id="irregularity">⚠ Irregularity: the sample submission is a copy of the labels</h2>
{note("warn", f'''The problem page states: <em>"A sample submission that predicts total fault absence
is provided for your reference."</em> (<a href="{PROB}#submission-format">source</a>)<br><br>
Measured instead: <code>example_submission.tif</code> contains
<b>{s['sample_positive_px']:,}</b> positive pixels — identical to <code>existing_faults.tif</code>
({s['labels_positive_px']:,}). Binary content identical across all
{s['n_pixels_compared']:,} commonly-valid pixels: <b>{s['binary_content_identical_on_common_valid']}</b>.<br><br>
<b>Why it matters:</b> anyone using the "sample" as a zero-filled template gets a file pre-populated
with the known faults. <b>Practical impact:</b> none for us — we write submissions from the sample's
<em>georeferencing only</em> and fill values from the model. <b>Flagged for organiser review.</b>''')}""")

    if dem:
        out.append(f"""<h2>1 m DEM tile list</h2>
<p>The competition provides <code>1m_DEM_links.csv</code>; the public mirror is a PDF. Measured: that
PDF <b>has no text layer</b> — pypdf, pdftotext and pdfplumber each return 0 URLs. It is a scan.</p>
<table class="kv"><tbody>
<tr><th>OCR (tesseract, 300 DPI)</th><td>{dem.get('ocr_pairs_parsed', 0):,} (project, tile) pairs parsed</td></tr>
<tr><th>Confirmed against the USGS bucket</th><td><b>{dem.get('n_unique_tiles_confirmed', 0):,}</b> unique tiles</td></tr>
<tr><th>Unmatched (flagged)</th><td>{dem.get('n_unmatched', 0)}</td></tr>
</tbody></table>
{note("ok", '''<b>Why no URL here was typed by a machine-guess.</b> OCR of this scan corrupts
characters — <code>2020</code> reads as <code>202@</code>, underscores become spaces,
<code>QL1</code>/<code>QLi</code> are ambiguous. Rather than repair characters and hope, the parser
extracts only the <em>structure</em> (project name + <code>x##y###</code> tile id) and then resolves
every URL against a live <code>ListObjectsV2</code> enumeration of the official USGS 3DEP bucket.
Emitted URLs are verbatim bucket keys. Anything unmatched is listed as an irregularity, never
guessed.''')}
<p>Full list with provenance: <a href="{REPO}/blob/main/data/dem_links.json"><code>data/dem_links.json</code></a></p>""")

    if tr and tr.get("encoding_bytes"):
        rows = "".join(f"<tr><td><code>{e(k)}</code></td><td>{fmt_bytes(v)}</td></tr>"
                       for k, v in tr["encoding_bytes"].items())
        out.append(f"""<h2>Working around a restricted network</h2>
<p>The development sandbox can reach only <code>github.com</code> and <code>pypi.org</code>; Dropbox,
S3, the Azure host serving Actions artifacts, and DrivenData itself are all blocked. Data is
therefore fetched by a GitHub Actions runner, which has open egress, and results return as commits.
A {fmt_bytes(tr.get('cropped_cube_raw_bytes'))} raw feature cube compresses to:</p>
<table><thead><tr><th>Encoding</th><th>Size</th></tr></thead><tbody>{rows}</tbody></table>
<p>Still too large to commit, so a <b>512×512 window of the real rasters</b> is committed instead
(<code>data/fixture/</code>, ~5 MB, int16-quantised with measured round-trip error 1.6×10⁻⁵ of each
band's range). That fixture is what lets the pipeline be developed and tested in-sandbox against
true band semantics.</p>""")

    if inv:
        rows = "".join(f'<tr><td><code>{e(f["name"])}</code></td><td>{fmt_bytes(f["bytes"])}</td>'
                       f'<td class="mono small">{e(f["sha256"])}</td></tr>' for f in inv["files"])
        out.append('<h2>Checksums</h2><table><thead><tr><th>File</th><th>Size</th>'
                   f'<th>sha256</th></tr></thead><tbody>{rows}</tbody></table>')

    return page("Data", "data.html", "\n".join(out),
                "Exactly what the competition files contain — measured, with the irregularities found.")


def _scoring_universe(ev: dict) -> str:
    """What the metric is computed AGAINST - the fact every other decision depends on.

    Rendered from data/evidence/rules_quotes.json, which scripts/verify_rules_quotes.py
    writes by extracting the canonical rules PDF and asserting each sentence appears
    verbatim.  If that evidence is absent the section says so instead of paraphrasing.
    """
    rq = ev.get("rules_quotes")
    head = f"""<h2>What the metric is actually computed against</h2>
<p>Both prize phases are scored on the <b>new fault dataset</b> — faults that are <em>not</em> in the
public catalogue the competition hands out for training. The training labels are the existing fault
data. The two populations are disjoint by construction, which is the single most consequential fact
in this competition:</p>"""
    if not rq:
        return head + note("warn", """The verbatim rules quotations have not been machine-verified in
this checkout yet. Run <code>python scripts/verify_rules_quotes.py --url
https://docs.nlr.gov/docs/fy26osti/96647.pdf</code> (or the <em>Verify official sources</em> workflow,
which also checks the PDF's sha256 against the inventoried data-tab copy). Until then, treat the
statement above as a claim derived from the <a href="%s">problem description</a>, not as a verified
quotation.""" % PROB)

    rows = "".join(
        f'<tr><td class="mono small">{e(q["id"])}</td><td>{e(q["section"])}</td>'
        f'<td>“{e(q["quote"])}”</td>'
        f'<td class="num">{"✔" if q.get("exact_match") else "✘"}</td></tr>'
        for q in rq["quotes"])
    # Schema note (fixed 2026-09-16, session 6): this badge used to read the keys
    # `verification` / `document`, which scripts/verify_rules_quotes.py has not written since the
    # report was reshaped to `summary` / `source` — so every build since then printed
    # "INCOMPLETE (0/0)" next to a table of 19 verified quotes, contradicting the overview page
    # that reads the same file correctly.  Read the current schema; fall back to counting the
    # quotes themselves if `summary` is ever absent, so the badge degrades to a recount, never
    # to a false 0/0 again.
    s = rq.get("summary") or {}
    src = rq.get("source") or rq.get("document", {})
    n_quotes = int(s.get("n_quotes") or len(rq["quotes"]))
    n_found = int(s.get("n_found", sum(1 for q in rq["quotes"] if q.get("exact_match"))))
    all_ok = bool(s.get("all_found", n_found == n_quotes and n_quotes > 0))
    doc_url = str(src.get("canonical_url") or src.get("url") or "")
    if not doc_url.startswith("http"):
        doc_url = RULES            # a local extraction path is not a link (cf. build_index)
    badge = note("ok", f"""<b>{n_found}/{n_quotes} quoted
sentences verified verbatim</b> against <code>{e(doc_url)}</code>
(sha256 <span class="mono small">{e(str(src.get("sha256", ""))[:16])}…</span>,
retrieved {e(rq["generated_utc"])}).
Method: {e(rq.get("method", ""))}.""") if all_ok else note(
        "warn", f"Quotation verification is INCOMPLETE ({n_found}/"
                f"{n_quotes}). Do not rely on the table below until it is fixed.")
    return head + badge + f"""<table><thead><tr><th>id</th><th>section</th><th>verbatim quotation</th>
<th>verified</th></tr></thead><tbody>{rows}</tbody></table>""" + note("warn", """<b>Consequence for
everything else in this repository.</b> A model that reproduces <code>labels.tif</code> perfectly scores
~1.0 against the catalogue and ~0 against the competition target: the scored faults are precisely the
ones missing from the catalogue. So the catalogue DTI quoted throughout this site is a
<em>plumbing monitor</em>, not a leaderboard proxy — useful because it proves the metric, the loss, the
tiling and the writer agree, and <em>not</em> useful for choosing between models. The quantities that
speak to the real objective are in <code>src/discovery.py</code>: <code>novel_fraction</code> (share of
emitted probability mass farther than R from any catalogued fault) and
<code>candidate_new_faults</code> (connected components of the prediction that touch no catalogued
fault). A submission of pure noise also has <code>novel_fraction ≈ 1</code>, so those diagnostics are
never read alone — they are read next to the catalogue DTI, the emitted area and the component sizes.""")


def build_metric(ev: dict) -> str:
    ms = ev.get("metric_strategy")
    body = [f"""<h2>Definition</h2>
<p>Scoring is a <b>distance-weighted Tversky index</b> with α=0.2, β=0.8 and a triangular kernel of
range R=300 m (3 px at 100 m) — <a href="{PROB}#performance-metric">official definition</a>.
Our implementation is <code>src/metrics.py</code>; its self-test checks it against a brute-force
transcription of the formulas and reproduces the worked example's 0.60.</p>
<pre class="math">TP_w = Σ<sub>g∈G</sub> max<sub>x:d(x,g)≤R</sub> p(x)·k(d(x,g))
FP_w = Σ<sub>x:p(x)&gt;0</sub> p(x)·[1 − max<sub>g∈G</sub> k(d(x,g))]
FN_w = Σ<sub>g∈G</sub> [1 − max<sub>x:d(x,g)≤R</sub> p(x)·k(d(x,g))]
DTI  = TP_w / (TP_w + α·FP_w + β·FN_w + ε)</pre>

<h2>The rearrangement that matters</h2>
<p>From the two sums, <code>TP_w + FN_w = |G|</code> holds <em>identically</em>, for any prediction.
Substituting:</p>
<pre class="math big">DTI = TP_w / ( 0.2·(TP_w + FP_w) + 0.8·|G| )</pre>
<p>So <code>TP_w</code> and <code>FP_w</code> enter with the <b>same coefficient</b>. Probability mass
costs the same wherever you put it; it earns credit only when it is the strongest mass within 3 px of
a ground-truth pixel. And <code>TP_w</code> saturates at 1 per ground-truth pixel, so extra mass on an
already-covered fault is pure cost. <code>scripts/metric_strategy.py</code> asserts this identity
against the direct computation on every row below.</p>"""]

    if ms:
        rows = "".join(
            f'<tr class="{"hl" if r["strategy"].startswith(("all ones", "25%")) else ""}">'
            f'<td>{e(r["strategy"])}</td><td class="num"><b>{r["dti"]:.4f}</b></td>'
            f'<td class="num">{r["TP_w"]:,.0f}</td><td class="num">{r["FP_w"]:,.0f}</td>'
            f'<td class="num">{r["mass"]:,.0f}</td></tr>' for r in ms["rows"]
        )
        body.append(f"""<h2>Measured baselines</h2>
<p>Computed on a real 512×512 window of the competition labels (|G| = {ms['n_ground_truth']:,} fault
pixels, {ms['n_valid_pixels']:,} valid pixels). Reproduce:
<code>python scripts/metric_strategy.py</code></p>
<table class="metric"><thead><tr><th>Strategy</th><th>DTI</th><th>TP_w</th><th>FP_w</th>
<th>mass emitted</th></tr></thead><tbody>{rows}</tbody></table>""")
        body.append(note("warn", """<b>The counter-intuitive result.</b> α=0.2 / β=0.8 reads as
“false negatives hurt 4× more, so predict generously”. The measurement says the opposite: blanket
coverage scores <b>0.096</b>, while a precise quarter of the faults scores <b>0.554</b> — about 6×
better from 200× less predicted mass. β multiplies FN_w, which is capped at |G|; α multiplies FP_w,
which grows with the <em>area</em> you paint, and there are ~50× more non-fault pixels than fault
pixels. The per-unit discount loses to the count."""))
        body.append("""<h2>Consequences for the model</h2>
<ul>
<li><b>Be sparse, thin and confident.</b> Dilating perfect predictions by one pixel costs 12 points
of DTI (0.9999 → 0.8818); by three pixels, 41 points.</li>
<li><b>Thin, but not to nothing.</b> Faults are 1-px lineaments at 100 m and
<code>src/submission_optim.py</code> applies a probability floor plus distance-R
dominating thinning; the pooled search selects <code>thin=True</code> essentially
always. But the width of what is kept is a separate decision, and against the public
labels it is <em>not</em> zero &mdash; see <a href="#width">the measured width curve</a>.</li>
<li><b>Recall still matters most among <em>correct</em> predictions</b> — DTI is near-linear in the
fraction of faults found (0.554 → 0.794 → 0.917 for 25/50/75% precise recall).</li>
<li><b>Beat 0.096.</b> A model scoring under the blanket-coverage floor is worse than a constant.</li>
</ul>""")
    else:
        body.append(missing("Measured baselines.", "python scripts/metric_strategy.py"))

    if ev.get("robustness"):
        _r0 = ev["robustness"]["rows"]
        _base = next((r for r in _r0 if r["dilate"] == 0), _r0[0])
        _best = max(_r0, key=lambda r: max(v["mean"] for v in r["per_shift"].values()))
        gain_txt = ("the skeleton (0 px) keeps {:,} px and scores {:.4f}, while a {}-px band keeps "
                    "{:,} px and scores {:.4f} - the operator family, not the floor, was the binding "
                    "constraint.".format(_base["kept_px"], _base["per_shift"]["0"]["mean"],
                                         _best["dilate"], _best["kept_px"],
                                         _best["per_shift"]["0"]["mean"]))
    else:
        gain_txt = ""
    rb = ev.get("robustness")
    if rb:
        _rows = []
        for r in rb["rows"]:
            per = r["per_shift"]
            _rows.append('<tr><td class="num">{}</td><td class="num">{:,}</td>{}</tr>'.format(
                r["dilate"], r["kept_px"],
                "".join('<td class="num">%.4f<br><span class="muted small">worst %.4f</span></td>'
                        % (per[k]["mean"], per[k]["worst"])
                        for k in sorted(per, key=lambda s: int(s)))))
        cols = "".join('<th>labels shifted &plusmn;%s px</th>' % k
                       for k in sorted(rb["rows"][0]["per_shift"], key=lambda s: int(s)))
        body.append("""<h2 id="width">How wide should the line be? &mdash; measured</h2>
<p>TP<sub>w</sub> takes a <em>max</em> within R = %d px, so a prediction up to that far from a
label still earns full credit, while FP costs 0.2 per unit of mass and a missed label costs 0.8.
That makes the <em>width</em> of the emitted line a first-class decision: a skeleton scores zero
on a fault it missed by more than R, while a band of k pixels survives k px of localisation error.
The scored faults are new to the expert-reviewed dataset (rules &sect;1.1/&sect;3.5) and the model
has never seen them, so its localisation error there is strictly larger than on the catalogue.</p>
<p>Measured on the one window where a real written submission and the official label raster
coexist (%s): %s</p>
<table><thead><tr><th>band (px)</th><th>pixels kept</th>%s</tr></thead><tbody>
%s
</tbody></table>
%s%s""" % (
            rb["R_pixels"], rb.get("window") or "whole raster", gain_txt, cols, "".join(_rows),
            note("warn", "<b>What this is and is not.</b> The labels here are the <em>public "
                         "catalogue</em>, not the scored set, and shifting them is a stress test of "
                         "the writing operator, not a measurement of the competition metric. It is "
                         "reported because the same asymmetry applies with more force to faults the "
                         "model has never seen."),
            note("info", "Because of this the shaping search now searches the emission width too "
                         "(<code>--dilate-grid</code>), and <code>--calibrate loo</code> re-fits the "
                         "floor on the folds that are <em>not</em> being scored, so the reported mean "
                         "is not selection-optimistic.")))

    body.append(_scoring_universe(ev))
    body.append(f"""<h2>Remaining caveats</h2>
<ul>
<li>|G| for the hidden test set is unknown, so the <code>0.8·|G|</code> floor is unknown. Every
absolute DTI on this page is a <em>monitor</em>; only ratios and identities carry over.</li>
<li>ε is not specified on the problem page; we use 1×10⁻⁷. Negligible here, recorded for exactness.</li>
<li>The public leaderboard is scored on a public <em>split</em> of the same new-fault dataset, so it is
the first honest signal; the private split and the Phase-2 revision are hidden.</li>
</ul>""")
    return page("Metric", "metric.html", "\n".join(body),
                "The scoring function, rearranged — and what it actually pays for.")


def build_method(ev: dict) -> str:
    return page("Method", "method.html", f"""
<h2>Baseline we build on</h2>
<p>The organisers' <a href="{REFSOL}">reference solution</a> (Prof. John Lipor) trains a U-Net
(ResNet-18 encoder, ImageNet weights) on 128-px patches over 5 Monte-Carlo train/test splits with
<code>TverskyLoss(α=0.2, β=0.8)</code>, AdamW at 1×10⁻⁴, 5 epochs, and stitches patch predictions
back into a full raster. Its patching creates the test patches first and zeroes them in the global
image so training cannot leak test labels.</p>

<h2>What we change, and why</h2>
<table class="cmp"><thead><tr><th>Choice</th><th>Reference</th><th>Here</th><th>Reason</th></tr></thead>
<tbody>
<tr><td>Loss</td><td>pixel-wise Tversky</td><td>differentiable <em>distance-weighted</em> Tversky
 + BCE + focal</td><td>The metric credits a prediction within 3 px of truth. A pixel-wise loss
 punishes exactly the rasterisation offset the organisers deliberately forgave.</td></tr>
<tr><td>Model selection</td><td>final epoch</td><td>best epoch by DTI on the <em>stitched global</em>
 held-out map</td><td>DTI is not decomposable over patches — the real scorer sees one continuous
 raster, so selection must too.</td></tr>
<tr><td>Submission shaping</td><td>none (raw probabilities)</td><td>probability floor + distance-R
 thinning, tuned on pooled held-out splits</td><td>Follows directly from the metric algebra: TP
 saturates, FP is an area sum. Measured to help on every run so far.</td></tr>
<tr><td>Negatives</td><td>fault-containing patches only</td><td>fraction of empty patches retained</td>
 <td>Without negatives the model never learns what "no fault" looks like and over-predicts — costly
 when FP is an area sum.</td></tr>
<tr><td>Normalisation</td><td>global min–max</td><td>percentile-clipped robust z-score, statistics
 persisted</td><td>Magnetic/gravity bands are heavy-tailed; a single outlier crushes min–max. Saved
 stats keep training and inference identical (required for reproducibility).</td></tr>
<tr><td>Inference</td><td>non-overlapping patches</td><td>dense sliding window, Gaussian blending,
 8-way TTA</td><td>Box-averaging leaves visible seams; seams are FP mass.</td></tr>
</tbody></table>

<h2>Guarding against leakage and self-deception</h2>
<ul>
<li>Test windows are cut and zeroed globally <em>before</em> overlapping training windows are sampled,
    and windows overlapping test area beyond a threshold are dropped.</li>
<li>The false-positive weight map is cropped from a <em>global</em> distance transform, so predictions
    near a patch border are not spuriously penalised.</li>
<li>Local scores against the public labels are reported as <b>optimistic</b> wherever they appear —
    those are the labels the model trained on, and they are not the test set.</li>
<li><code>src/metrics.py --self-test</code> runs 8 checks including fast-vs-brute-force agreement and
    the official worked example.</li>
</ul>

<h2>The strategic problem nobody can shortcut</h2>
<p>The scored faults are <em>the ones missing from the public database</em>. A model that merely fits
the public labels is fitting the wrong target. Two implications drive the design:</p>
<ol>
<li><b>Don't over-fit the known faults.</b> Held-out DTI against public labels is a plumbing check,
not a leaderboard proxy.</li>
<li><b>Generalise geophysically.</b> The useful signal is the physics that <em>produces</em> a fault
expression — magnetic/gravity gradient discontinuities, strain-rate concentration, detrended-elevation
lineaments — which is why all 19 bands are kept and line-enhancement filtering is available in
post-processing. The Final Prize Round explicitly rewards flagging faults experts then confirm.</li>
</ol>
""", "How this differs from the reference solution, and the reasoning behind each change.")


def build_results(ev: dict) -> str:
    runs = ev.get("runs", [])
    body = [f"""<h2>Honest status</h2>
{note("bad", '''<b>A green workflow is not evidence.</b> The 6-fold ensemble run
<code>35042805806</code> trained every fold for 2 h 36 min and then crashed while writing the
submission (<code>RasterBlockError: the height and width of TIFF dataset blocks must be multiples of
16</code>). The job was reported <b>successful</b>, because the step piped Python into <code>tee</code>
without <code>pipefail</code>, and the evidence it committed was self-incriminating:
<code>data/evidence/runs/35042805806/submission.tif</code> is <b>110 bytes</b> (a GDAL stub) and
<code>validation.log</code> is an argparse usage dump. Fixed on 2026-09-16: a read-back-verifying
writer (<code>src/submission_io.py</code>), <code>pipefail</code> on every piped step, and a commit gate
that ships <code>FAILED.json</code> instead of a stub. The rebuilt submission is the newest run below.''')}
{note("warn", '''The pipeline runs end to end on the real competition rasters and every number below
is measured, but it is <b>not yet competitive</b>: the first full-scale run was a 2-epoch MobileNetV2
smoke test that scored <em>below</em> the trivial blanket-coverage baseline, which is recorded here as
a negative result rather than dressed up. And every DTI on this page is computed against the
<em>known</em> catalogue, which is not the scored universe (see <a href="metric.html">Metric</a>).''')}"""]

    if runs:
        for r in runs:
            s = r.get("summary", {})
            body.append(f"""<h3>Run <code>{e(s.get('run_id', '?'))}</code></h3>
<table class="kv"><tbody>
<tr><th>Profile</th><td>{e(s.get('profile', '—'))}</td></tr>
<tr><th>Runner</th><td>{e(s.get('runner', '—'))}</td></tr>
<tr><th>Commit</th><td class="mono small">{e(str(s.get('commit', ''))[:12])}</td></tr>
<tr><th>Submission</th><td>{fmt_bytes(s.get('submission_bytes'))},
  sha256 <span class="mono small">{e(str(s.get('submission_sha256', ''))[:16])}…</span></td></tr>
</tbody></table>""")
            hist = r.get("history")
            if hist:
                rows = "".join(
                    f'<tr><td>{h["epoch"]}</td><td class="num">{h["loss"]:.4f}</td>'
                    f'<td class="num">{h["dti_raw"]:.4f}</td><td class="num">{h["dti_shaped"]:.4f}</td>'
                    f'<td class="num">{h["TP_w"]:,.0f}</td><td class="num">{h["FP_w"]:,.0f}</td></tr>'
                    for h in hist
                )
                body.append('<table><thead><tr><th>Epoch</th><th>Loss</th><th>DTI raw</th>'
                            '<th>DTI shaped</th><th>TP_w</th><th>FP_w</th></tr></thead>'
                            f"<tbody>{rows}</tbody></table>")
            if r.get("score"):
                body.append(f'<p><b>Full-raster score vs public labels:</b> '
                            f'<code>{e(r["score"].strip())}</code></p>')
            b = r.get("blend")
            if b:
                shp = b.get("shaping", {})
                sub = b.get("submission", {})
                mass = b.get("probability_mass", {})
                loc = b.get("local_score_vs_known") or {}
                folds = ", ".join(f["dir"] for f in b.get("folds", []))
                body.append(f"""<h4>Ensemble blend ({e(str(b.get('generated_utc', '')))})</h4>
<table class="kv"><tbody>
<tr><th>Folds blended</th><td>{b.get('n_folds', '—')} — <span class="mono small">{e(folds)}</span></td></tr>
<tr><th>Pooled shaping</th><td>t0 = <b>{e(str(round(shp.get('t0', float('nan')), 3)))}</b>,
  thin = <b>{e(str(shp.get('thin')))}</b> — mean held-out DTI
  <b>{shp.get('mean_heldout_dti', float('nan')):.4f}</b> (unshaped {shp.get('unshaped_mean_heldout_dti', float('nan')):.4f})</td></tr>
<tr><th>Probability mass</th><td>{mass.get('pre_shaping', 0):,.0f} → {mass.get('post_shaping', 0):,.0f}
  (shaping compression ×{round(mass.get('collapse_factor') or 0, 1)})</td></tr>
<tr><th>Fold weights</th><td>{e(str(b.get('fold_weights')))}</td></tr>
<tr><th>Submission</th><td>{fmt_bytes(sub.get('bytes'))}, nonzero {sub.get('nonzero_px', 0):,} px,
  sha256 <span class="mono small">{e(str(sub.get('sha256', ''))[:16])}…</span></td></tr>
<tr><th>Info: DTI vs <em>known</em> faults</th><td>{loc.get('dti_known_faults', float('nan')):.4f}
  (blanket-ones floor {loc.get('blanket_ones_dti', float('nan')):.4f}) — wrong-universe number, see caveat</td></tr>
</tbody></table>""")
                fold_rows = "".join(
                    f'<tr><td>{e(fr["dir"])}</td><td>{e(", ".join(m or "?" for m in fr["models"]))}</td>'
                    f'<td class="num">{", ".join(f"{d:.4f}" for d in fr["fold_best_dti"] if d is not None) or "—"}</td></tr>'
                    for fr in b.get("folds", []))
                if fold_rows:
                    body.append('<table><thead><tr><th>Fold</th><th>Model(s)</th>'
                                '<th>Best held-out shaped DTI</th></tr></thead>'
                                f"<tbody>{fold_rows}</tbody></table>")
                disc = b.get("discovery_vs_known_catalog")
                if disc:
                    nm = disc.get("novel_mass", {})
                    pt = (disc.get("per_threshold") or {}).get("0.5", {})
                    body.append(f"""<h5>Discovery diagnostics (vs the known catalogue)</h5>
<table class="kv"><tbody>
<tr><th>novel_fraction</th><td><b>{nm.get('novel_fraction', float('nan')):.3f}</b> of emitted
  probability mass sits farther than R=3 px from any catalogued fault</td></tr>
<tr><th>mass</th><td>{nm.get('prob_mass', 0):,.0f} total → {nm.get('novel_mass', 0):,.0f} novel</td></tr>
<tr><th>candidate new faults</th><td>{pt.get('n_novel_components', 0):,} components
  ({pt.get('novel_px', 0):,} px) do not touch the catalogue at p&gt;0.5; largest
  {pt.get('largest_novel_px', 0):,} px</td></tr>
<tr><th>catalogue recall @R</th><td>{disc.get('catalog_recall_R_t0.5', 0.0):.3f} of catalogued fault
  pixels have a prediction within R (higher = more catalogue-driven)</td></tr>
</tbody></table>
<p class="small">These are the numbers that speak to the scored universe. Read together: high
catalogue recall with a low <code>novel_fraction</code> means the submission mostly restates the
catalogue (poor against new faults); a high <code>novel_fraction</code> with a large component count
means it is proposing candidates (what Phase 2 rewards if experts confirm them).</p>""")
                cal = shp.get("calibration_table") or []
                if cal:
                    best_t = shp.get("t0")
                    best_th = shp.get("thin")
                    crows = ""
                    for row in cal:
                        hl = ' class="hl"' if (row.get("t0") == best_t and row.get("thin") == best_th) else ""
                        if row.get("t0") is None:
                            tcell, thcell = "unshaped", "—"
                        else:
                            tcell, thcell = format(row["t0"], ".2f"), ("yes" if row["thin"] else "no")
                        crows += ('<tr' + hl + '><td class="num">' + tcell + "</td><td>" + thcell
                                  + '</td><td class="num">' + format(row["mean_dti"], ".4f") + "</td></tr>")
                    body.append("<details><summary>Full shaping calibration table (highlighted row = chosen)</summary>"
                                "<table><thead><tr><th>t0 floor</th><th>thin</th>"
                                "<th>mean held-out DTI</th></tr></thead>"
                                "<tbody>" + crows + "</tbody></table></details>")
    else:
        body.append(missing("Training run reports.", "GitHub Actions → “Train and build submission”"))

    body.append("""<h2>What the numbers mean</h2>
<ul>
<li><b>DTI shaped &gt; DTI raw</b> on every run so far — the floor-plus-thinning step consistently
    helps, exactly as the metric algebra predicts.</li>
<li><b>FP_w dominates.</b> The smoke model emits far too much diffuse mass. This is the single
    biggest lever available, and it is an <em>output shaping</em> problem as much as a modelling one.</li>
<li><b>Local scores are optimistic.</b> They are computed against the labels used in training and are
    not the private test set.</li>
</ul>

<h2>Next steps, in priority order</h2>
<ol>
<li><b>Optimise for the scored universe, not the catalogue.</b> The scored faults are missing from
    <code>labels.tif</code>, so model selection, shaping calibration and fold weighting must be anchored
    on <code>src/discovery.py</code> diagnostics plus a spatial-block hold-out instead of catalogue DTI.
    This is a measurement-protocol change before it is a modelling change.</li>
<li><b>Parallel 6-fold ensemble on CPU runners</b> — implemented as the
    <em>Train MC ensemble</em> workflow (<code>configs/config_ci_ensemble.yaml</code>:
    UNet++ / DeepLabV3+ / U-Net × resnet34 at patch 256, 8-way TTA, pooled shaping calibration).
    The first full run is the current frontier until a GPU exists.</li>
<li><b>GPU training at full capacity</b> — <code>configs/config.yaml</code> (EfficientNet-B5, 10 MC
    splits, 60 epochs, 4 architectures) remains the config to move to; a 24 GB card turns the
    ~4 h CPU profile into under an hour and roughly doubles fold count.</li>
<li><b>1 m DEM derivatives</b> from the 716 confirmed tiles — lineament and scarp signal at 100 m is
    the most direct physical evidence of surface faulting (code ready:
    <code>src/external_data.py</code>, <code>scripts/download_dem_tiles.py</code>).</li>
<li><b>Frangi line-enhancement A/B</b> on the blended map, and self-training with high-confidence
    pseudo-labels — both proposed in <code>SUGGESTIONS.md</code>, not yet measured.</li>
</ol>""")
    return page("Results", "results.html", "\n".join(body),
                "Measured outcomes, including the ones that did not work.")


def build_sources(ev: dict) -> str:
    lv = ev.get("linkver")
    body = [f"""<h2>Primary sources</h2>
<table><thead><tr><th>What</th><th>Link</th></tr></thead><tbody>
<tr><td>Competition home (rules, dates, prizes)</td><td><a href="{COMP}">{COMP}</a></td></tr>
<tr><td>Problem description (task, metric, submission format)</td><td><a href="{PROB}">{PROB}</a></td></tr>
<tr><td>About page</td><td><a href="{ABOUT}">{ABOUT}</a></td></tr>
<tr><td>Data download tab (login required)</td><td><a href="{DATA_TAB}">{DATA_TAB}</a></td></tr>
<tr><td>Official rules PDF</td><td><a href="{RULES}">{RULES}</a></td></tr>
<tr><td>Reference solution</td><td><a href="{REFSOL}">{REFSOL}</a></td></tr>
<tr><td>GeoDAWN survey (USGS)</td><td><a href="https://www.usgs.gov/data/geodawn-airborne-magnetic-and-radiometric-surveys-northwestern-great-basin-nevada-and">USGS GeoDAWN</a></td></tr>
<tr><td>GeoDAWN data release (ScienceBase)</td><td><a href="https://www.sciencebase.gov/catalog/item/657e1d85d34e23d3533209f7">ScienceBase 657e1d85…</a></td></tr>
<tr><td>INGENIOUS project (GBCGE)</td><td><a href="https://gbcge.org/current-projects/ingenious/">gbcge.org</a></td></tr>
<tr><td>INGENIOUS data (OpenEI GDR)</td><td><a href="https://gdr.openei.org/submissions/1391">GDR 1391</a></td></tr>
<tr><td>USGS Quaternary faults</td><td><a href="https://www.sciencebase.gov/catalog/item/589097b1e4b072a7ac0cae23">ScienceBase 589097b1…</a></td></tr>
<tr><td>USGS 3DEP 1 m elevation</td><td><a href="https://www.usgs.gov/3d-elevation-program">3DEP</a> · <a href="https://apps.nationalmap.gov/downloader/">downloader</a></td></tr>
</tbody></table>
{note("ok", '''<b>Licensing.</b> The external data used here is US Government work (USGS: public
domain) or openly licensed (INGENIOUS via OpenEI GDR). The rules permit additional data provided the
licence allows use in the challenge and sharing with the sponsor
(<a href="''' + PROB + '''#external-datasets">external datasets</a>).''')}"""]

    sb = ev.get("sb")
    if sb:
        files_rows = []
        for it in sb["items"]:
            fl = "<br>".join(f'{e(f["name"])} <span class="muted">({e(f["size"])})</span>'
                             for f in it.get("files", [])) or "-"
            files_rows.append(f"""<tr>
<td><a href="{it['sciencebase_url']}">{e(it['title'])}</a><br>
    <code>{e(it['doi'])}</code> <span class="muted">({e(it['catalog_id'])})</span></td>
<td>{e(it.get('citation', ''))}</td>
<td>{fl}</td>
<td>{e(it.get('role', ''))}</td></tr>""")
        body.append(f"""<h2>INGENIOUS sub-datasets &mdash; direct DOI verification</h2>
<p>Three of the catalogued external sources are USGS data releases produced for the same DOE
project that generated the competition data. Each DOI below was followed to its ScienceBase
landing page and the title, citation and attached files were read off that page
({e(sb['generated_utc'])}).</p>
<table><thead><tr><th>Release</th><th>Citation</th><th>Attached files</th><th>Role here</th></tr>
</thead><tbody>
{''.join(files_rows)}
</tbody></table>
{note("info", "<b>Irregularity, recorded not hidden.</b> " + e(sb['irregularity']))}
{note("ok", "<b>Why this matters for the leaderboard.</b> The scored faults are the ones "
            "<em>missing</em> from the INGENIOUS catalogue, and the detrended-elevation and "
            "geophysics grids are that project's own fault-emphasising products: free, "
            "public-domain, officially released, and already inside the study area. They are the "
            "lowest-risk additional inputs to test against the negative-sampling baseline "
            "(see <a href='results.html'>Results</a>).")}""")

    if lv:
        c = lv["summary_counts"]
        def _cls(k):
            if k.startswith("OK"):
                return "ok"
            if k.startswith(("LOGIN_REQUIRED", "BOT_BLOCKED")):
                return "info"
            return "bad"

        chips = " ".join(f'<span class="pill {_cls(k)}">{e(k)}: {v}</span>'
                         for k, v in sorted(c.items()))
        body.append(f"""<h2>Live link verification</h2>
<p>Every URL in <a href="{REPO}/blob/main/docs/data_catalog.csv"><code>data_catalog.csv</code></a> is
re-fetched by <code>scripts/verify_links.py</code> on a runner and its real HTTP status recorded.
Checked {lv['n_unique_urls']} unique URLs across {lv['n_rows']} catalog rows
({e(lv['generated_utc'])}).</p>
<p>{chips}</p>""")
        exp = lv.get("expected_non_ok") or []
        if exp:
            rows = "".join(f'<tr><td><span class="pill info">{e(p["result"])}</span></td>'
                           f'<td class="small"><a href="{e(p["url"])}">{e(p["url"][:110])}</a></td></tr>'
                           for p in exp)
            body.append('<h3>Expected non-200 responses (not defects)</h3>'
                        '<table><thead><tr><th>Status</th><th>URL</th></tr></thead>'
                        f'<tbody>{rows}</tbody></table>')
            body.append(note("ok", """<b>Why these are not counted as broken.</b>
<code>LOGIN_REQUIRED</code> on the DrivenData data tab is the competition working as designed.
<code>BOT_BLOCKED_403/401</code> is Cloudflare-style bot mitigation at academic publishers and
<code>doi.org</code>, which reject any non-browser client; the DOI remains the citable identifier.
Calling either one "broken" would itself be an inaccuracy, so they are reported separately."""))
        if lv.get("problems"):
            rows = "".join(f'<tr><td><span class="pill bad">{e(p["result"])}</span></td>'
                           f'<td class="small"><a href="{e(p["url"])}">{e(p["url"][:110])}</a></td></tr>'
                           for p in lv["problems"])
            body.append('<h3>Flagged for review</h3><table><thead><tr><th>Status</th><th>URL</th></tr>'
                        f'</thead><tbody>{rows}</tbody></table>')
            body.append(note("warn", "These need a human look — they are neither reachable nor "
                                     "explained by a login wall or publisher bot-blocking."))
        body.append(f'<p>Machine output: <a href="link_verification.json">link_verification.json</a> · '
                    f'<a href="data_catalog.verified.csv">data_catalog.verified.csv</a></p>')
    else:
        body.append(missing("Live link verification.", "python scripts/verify_links.py"))

    body.append(f"""<h2>Full catalog</h2>
<p><a href="data_catalog.csv">data_catalog.csv</a> — one row per source, with publisher, DOI, licence
and the role it plays here.</p>""")
    return page("Sources", "sources.html", "\n".join(body),
                "Every source, with its live-checked status.")


def build_reproduce(ev: dict) -> str:
    return page("Reproduce", "reproduce.html", f"""
<h2>Get the data</h2>
<p>The competition files require a DrivenData login. With an account:</p>
<pre><code>bash scripts/download_competition_data.sh   # Dropbox mirrors from the data tab
python scripts/prepare_data.py              # validates CRS, resolution, bounds, bands</code></pre>
<p><code>prepare_data.py</code> exits non-zero on any mismatch, so a bad download is caught before
hours of training.</p>

<h2>Train and build a submission</h2>
<pre><code># GPU box, full capacity
python -m src.train     --config configs/config.yaml
python -m src.inference --config configs/config.yaml --out submission.tif
python scripts/validate_submission.py --pred submission.tif --sample data/sample_submission.tif

# CPU, proves the pipeline on the real rasters
python -m src.train --config configs/config_ci_smoke.yaml

# CPU, ensemble: one fold (repeat per fold), raw map, then blend+shape across folds
python -m src.train --config configs/config_ci_ensemble.yaml --override training.mc_id=0
python -m src.inference --config configs/config_ci_ensemble.yaml --raw --out outputs/prob_raw.tif
python scripts/blend_submission.py --folds outputs_f0 outputs_f1 ... --out submission.tif

# In-sandbox, against the committed real-data fixture (no download needed)
python -m src.fixture                                    # verify the fixture
python -m src.train --config configs/config_fixture.yaml</code></pre>

<h2>Check the claims on this site</h2>
<pre><code>python src/metrics.py --self-test         # 8 checks incl. the official worked example
python scripts/metric_strategy.py         # regenerates the Metric page's table
python scripts/verify_links.py            # re-checks every source link over HTTP
python scripts/inspect_competition_data.py --data-dir data   # regenerates the Data page
python scripts/build_site.py              # rebuilds this site from the JSON above</code></pre>

<h2>Automation</h2>
<p>Two GitHub Actions workflows do the work that needs open network access:</p>
<ul>
<li><b>Fetch competition data</b> — downloads the files, measures them, OCRs the DEM PDF, resolves
tiles against the USGS bucket, verifies every link, builds the dev fixture, and commits the evidence
JSON back to the branch.</li>
<li><b>Train and build submission</b> — single-job smoke: train → inference → validation → scoring,
uploads <code>submission.tif</code> as an artifact.</li>
<li><b>Train MC ensemble (parallel folds) + blend</b> — six fold jobs train one MC split each
(<code>--override training.mc_id=F</code>) and blend the raw probability maps in a final job with one
shaping pass calibrated on the pooled held-out DTI. Reports and the shaped submission are committed
back to the branch under <code>data/evidence/runs/&lt;run_id&gt;/</code>.</li>
</ul>

<h2>Submitting</h2>
<p>Upload <code>submission.tif</code> via the Submit tab at
<a href="{COMP}">{COMP}</a>. Requirements checked by
<code>scripts/validate_submission.py</code>: single band, float32, values in [0,1], EPSG:32611,
100 m, identical grid and transform to the provided template
(<a href="{PROB}#submission-format">spec</a>). Note the competition requires choosing a
<b>single</b> submission for scoring in both rounds before the deadline.</p>
""", "Every command needed to rebuild the data, the model and this site.")


CSS = """
:root{
  --bg:#fbfaf9; --fg:#1c1917; --muted:#78716c; --line:#e7e5e4; --card:#fff;
  --accent:#b45309; --accent-dark:#78350f; --ok:#15803d; --warn:#b45309; --bad:#b91c1c;
  --mono:ui-monospace,SFMono-Regular,"SF Mono",Menlo,Consolas,monospace;
}
*{box-sizing:border-box}
html{-webkit-text-size-adjust:100%}
body{margin:0;background:var(--bg);color:var(--fg);
  font:16px/1.65 -apple-system,BlinkMacSystemFont,"Segoe UI",Inter,Roboto,Helvetica,Arial,sans-serif}
.wrap{max-width:1060px;margin:0 auto;padding:0 24px}
header{background:linear-gradient(160deg,#292524,#44403c);color:#fafaf9;padding:30px 0}
.brand{display:flex;align-items:center;gap:16px}
.logo{font-size:40px;line-height:1}
.name{font-size:1.45rem;font-weight:680;letter-spacing:-.02em}
.tag{color:#d6d3d1;font-size:.94rem;margin-top:3px}
nav{background:var(--card);border-bottom:1px solid var(--line);position:sticky;top:0;z-index:10}
nav .wrap{display:flex;gap:4px;overflow-x:auto}
nav a{padding:13px 15px;color:var(--muted);text-decoration:none;font-size:.93rem;font-weight:520;
  border-bottom:2px solid transparent;white-space:nowrap}
nav a:hover{color:var(--fg)}
nav a.active{color:var(--accent);border-bottom-color:var(--accent)}
main{padding:34px 0 60px}
h1{font-size:2rem;letter-spacing:-.025em;margin:0 0 6px;font-weight:700}
.lede{color:var(--muted);font-size:1.08rem;margin:0 0 26px}
h2{font-size:1.3rem;margin:36px 0 12px;letter-spacing:-.015em;padding-bottom:7px;
  border-bottom:1px solid var(--line);font-weight:650}
h3{font-size:1.05rem;margin:26px 0 9px;font-weight:620}
p{margin:11px 0}
a{color:var(--accent)}
a:hover{color:var(--accent-dark)}
code{font-family:var(--mono);font-size:.88em;background:#f5f5f4;padding:1.5px 5px;border-radius:4px}
pre{background:#292524;color:#e7e5e4;padding:16px 18px;border-radius:9px;overflow-x:auto;
  font-family:var(--mono);font-size:.86rem;line-height:1.6}
pre code{background:none;padding:0;color:inherit;font-size:1em}
pre.math{background:#f5f5f4;color:#1c1917;border-left:3px solid var(--accent)}
pre.math.big{font-size:1.02rem;font-weight:600;text-align:center}
table{width:100%;border-collapse:collapse;margin:14px 0;font-size:.9rem;
  background:var(--card);border:1px solid var(--line);border-radius:9px;overflow:hidden}
th,td{padding:9px 12px;text-align:left;border-bottom:1px solid var(--line);vertical-align:top}
thead th{background:#f5f5f4;font-weight:620;font-size:.82rem;text-transform:uppercase;
  letter-spacing:.04em;color:var(--muted)}
tbody tr:last-child td{border-bottom:none}
tbody tr:hover{background:#fafaf9}
table.kv th{width:190px;color:var(--muted);font-weight:560;background:#fafaf9}
td.num{text-align:right;font-variant-numeric:tabular-nums;font-family:var(--mono);font-size:.85rem}
tr.hl{background:#fffbeb}
tr.hl:hover{background:#fef3c7}
.mono{font-family:var(--mono)}
.small{font-size:.82rem}
table.bands td:nth-child(4){font-size:.85rem;color:#44403c}
.note{padding:14px 16px;border-radius:9px;margin:16px 0;font-size:.93rem;border:1px solid}
.note.ok{background:#f0fdf4;border-color:#bbf7d0}
.note.warn{background:#fffbeb;border-color:#fde68a}
.note.bad{background:#fef2f2;border-color:#fecaca}
.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(205px,1fr));gap:13px;margin:22px 0}
.stat{background:var(--card);border:1px solid var(--line);border-radius:11px;padding:15px 17px}
.stat .k{font-size:.76rem;text-transform:uppercase;letter-spacing:.05em;color:var(--muted);
  font-weight:620}
.stat .v{font-size:1.16rem;margin:5px 0 2px}
.stat .s{font-size:.82rem;color:var(--muted)}
.pill{display:inline-block;padding:2px 9px;border-radius:999px;font-size:.76rem;font-weight:620;
  margin:2px 3px 2px 0}
.pill.ok{background:#dcfce7;color:#14532d}
.pill.bad{background:#fee2e2;color:#7f1d1d}
.pill.info{background:#e0f2fe;color:#075985}
ol.findings li{margin:9px 0}
ul li,ol li{margin:5px 0}
table.cmp td:nth-child(4){color:#44403c;font-size:.87rem}
footer{border-top:1px solid var(--line);background:var(--card);padding:24px 0;
  color:var(--muted);font-size:.86rem}
footer p{margin:5px 0}
@media(max-width:640px){
  .wrap{padding:0 16px} h1{font-size:1.6rem}
  table{font-size:.83rem;display:block;overflow-x:auto}
  table.kv th{width:auto}
}
"""


def main() -> int:
    ev = {
        "inventory": load(ROOT / "data/evidence/inventory.json"),
        "rasters": load(ROOT / "data/evidence/rasters.json"),
        "labels": load(ROOT / "data/evidence/labels_summary.json"),
        "transfer": load(ROOT / "data/evidence/transfer_analysis.json"),
        "metric_strategy": load(ROOT / "data/evidence/metric_strategy.json"),
        "rules_quotes": load(ROOT / "data/evidence/rules_quotes.json"),
        "dem": load(ROOT / "data/dem_links.json"),
        "sb": load(ROOT / "data/evidence/sciencebase_dois.json"),
        "linkver": load(DOCS / "link_verification.json"),
        "robustness": load(ROOT / "data/evidence/shift_robustness.json"),
        "runs": [],
    }
    rd = ROOT / "data/evidence/runs"
    if rd.exists():
        for d in sorted(rd.iterdir(), reverse=True):
            if not d.is_dir():
                continue
            score = None
            sp = d / "local_score.log"
            if sp.exists():
                score = sp.read_text().strip().splitlines()[0] if sp.read_text().strip() else None
            ev["runs"].append({
                "summary": load(d / "run_summary.json") or {},
                "history": load(d / "train_history.json"),
                "score": score,
                "blend": load(d / "blend_report.json"),
            })

    DOCS.mkdir(exist_ok=True)
    (DOCS / "style.css").write_text(CSS)
    pages = {
        "index.html": build_index(ev),
        "data.html": build_data(ev),
        "metric.html": build_metric(ev),
        "method.html": build_method(ev),
        "results.html": build_results(ev),
        "sources.html": build_sources(ev),
        "reproduce.html": build_reproduce(ev),
    }
    for name, content in pages.items():
        (DOCS / name).write_text(content)
        print(f"wrote docs/{name} ({len(content):,} bytes)")

    have = [k for k, v in ev.items() if v]
    print(f"\nevidence present: {', '.join(have)}")
    absent = [k for k, v in ev.items() if not v]
    if absent:
        print(f"evidence MISSING (sections will say so): {', '.join(absent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
